<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PeNet" Version="6.1.2" />
    <PackageReference Include="SharpDivert" Version="1.1.0" />
    <PackageReference Include="System.Management" Version="10.0.12" />
    <PackageReference Include="Titanium.Web.Proxy" Version="7.0.6" />
  </ItemGroup>

</Project>